const administrativeData = {
    "Thái Nguyên": {
        "Thành phố Thái Nguyên": {
            "Phường Ba Hàng": {},
            "Phường Cam Giá": {},
            "Phường Chùa Hang": {},
            "Phường Đồng Bẩm": {},
            "Phường Đồng Quang": {},
            "Phường Gia Sàng": {},
            "Phường Hoàng Văn Thụ": {},
            "Phường Hương Sơn": {},
            "Phường Phú Xá": {},
            "Phường Quan Triều": {},
            "Phường Quang Trung": {},
            "Phường Quang Vinh": {},
            "Phường Tân Lập": {},
            "Phường Tân Long": {},
            "Phường Tân Thành": {},
            "Phường Tân Thịnh": {},
            "Phường Thịnh Đán": {},
            "Phường Tích Lương": {},
            "Phường Trung Thành": {},
            "Phường Trưng Vương": {},
            "Phường Túc Duyên": {},
            "Xã Cao Ngạn": {},
            "Xã Đồng Liên": {},
            "Xã Huống Thượng": {},
            "Xã Linh Sơn": {},
            "Xã Phúc Hà": {},
            "Xã Phúc Trìu": {},
            "Xã Phúc Xuân": {},
            "Xã Quyết Thắng": {},
            "Xã Tân Cương": {},
            "Xã Thịnh Đức": {},
            "Xã Tích Lương": {}
        },
        "Thành phố Sông Công": {
            "Phường Bách Quang": {},
            "Phường Cải Đan": {},
            "Phường Châu Sơn": {},
            "Phường Lương Châu": {},
            "Phường Mỏ Chè": {},
            "Phường Phố Cò": {},
            "Phường Thắng Lợi": {},
            "Xã Bá Xuyên": {},
            "Xã Bình Sơn": {},
            "Xã Tân Quang": {},
            "Xã Vinh Sơn": {}
        },
        "Thị xã Phổ Yên": {
            "Phường Ba Hàng": {},
            "Phường Bãi Bông": {},
            "Phường Bắc Sơn": {},
            "Phường Đồng Tiến": {},
            "Xã Đắc Sơn": {},
            "Xã Đông Cao": {},
            "Xã Hồng Tiến": {},
            "Xã Minh Đức": {},
            "Xã Nam Tiến": {},
            "Xã Phúc Tân": {},
            "Xã Phúc Thuận": {},
            "Xã Tân Hương": {},
            "Xã Tân Phú": {},
            "Xã Thành Công": {},
            "Xã Thuận Thành": {},
            "Xã Tiên Phong": {},
            "Xã Trung Thành": {},
            "Xã Vạn Phái": {}
        },
        "Huyện Phú Bình": {
            "Thị trấn Hương Sơn": {},
            "Xã Bảo Lý": {},
            "Xã Bàn Đạt": {},
            "Xã Đào Xá": {},
            "Xã Điềm Thụy": {},
            "Xã Đồng Liên": {},
            "Xã Hà Châu": {},
            "Xã Kha Sơn": {},
            "Xã Lương Phú": {},
            "Xã Nga My": {},
            "Xã Nhã Lộng": {},
            "Xã Tân Đức": {},
            "Xã Tân Hòa": {},
            "Xã Tân Khánh": {},
            "Xã Tân Kim": {},
            "Xã Tân Thành": {},
            "Xã Thanh Ninh": {},
            "Xã Thượng Đình": {},
            "Xã Úc Kỳ": {},
            "Xã Xuân Phương": {}
        },
        "Huyện Đồng Hỷ": {
            "Thị trấn Chùa Hang": {},
            "Thị trấn Trại Cau": {},
            "Xã Cây Thị": {},
            "Xã Hòa Bình": {},
            "Xã Hóa Thượng": {},
            "Xã Hóa Trung": {},
            "Xã Hợp Tiến": {},
            "Xã Khe Mo": {},
            "Xã Linh Sơn": {},
            "Xã Nam Hòa": {},
            "Xã Quang Sơn": {},
            "Xã Sảng Mộc": {},
            "Xã Tân Long": {},
            "Xã Tân Lợi": {},
            "Xã Văn Hán": {},
            "Xã Văn Lăng": {}
        },
        "Huyện Võ Nhai": {
            "Thị trấn Đình Cả": {},
            "Xã Bình Long": {},
            "Xã Cúc Đường": {},
            "Xã Dân Tiến": {},
            "Xã La Hiên": {},
            "Xã Lâu Thượng": {},
            "Xã Liên Minh": {},
            "Xã Nghinh Tường": {},
            "Xã Phú Thượng": {},
            "Xã Phương Giao": {},
            "Xã Sảng Mộc": {},
            "Xã Thần Sa": {},
            "Xã Thượng Nung": {},
            "Xã Tràng Xá": {},
            "Xã Vũ Chấn": {}
        },
        "Huyện Định Hóa": {
            "Thị trấn Chợ Chu": {},
            "Xã Bảo Cường": {},
            "Xã Bảo Linh": {},
            "Xã Bình Thành": {},
            "Xã Bình Yên": {},
            "Xã Bộc Nhiêu": {},
            "Xã Điềm Mặc": {},
            "Xã Định Biên": {},
            "Xã Đồng Thịnh": {},
            "Xã Kim Phượng": {},
            "Xã Lam Vỹ": {},
            "Xã Linh Thông": {},
            "Xã Phú Đình": {},
            "Xã Phú Tiến": {},
            "Xã Phúc Chu": {},
            "Xã Phượng Tiến": {},
            "Xã Quy Kỳ": {},
            "Xã Sơn Phú": {},
            "Xã Tân Dương": {},
            "Xã Tân Thịnh": {},
            "Xã Thanh Định": {},
            "Xã Trung Hội": {},
            "Xã Trung Lương": {}
        },
        "Huyện Đại Từ": {
            "Thị trấn Hùng Sơn": {},
            "Thị trấn Quân Chu": {},
            "Xã An Khánh": {},
            "Xã Bản Ngoại": {},
            "Xã Bình Thuận": {},
            "Xã Cát Nê": {},
            "Xã Cù Vân": {},
            "Xã Đức Lương": {},
            "Xã Hà Thượng": {},
            "Xã Hoàng Nông": {},
            "Xã Khôi Kỳ": {},
            "Xã Ký Phú": {},
            "Xã La Bằng": {},
            "Xã Lục Ba": {},
            "Xã Minh Tiến": {},
            "Xã Mỹ Yên": {},
            "Xã Na Mao": {},
            "Xã Phú Cường": {},
            "Xã Phú Lạc": {},
            "Xã Phú Thịnh": {},
            "Xã Phúc Lương": {},
            "Xã Phượng Tiến": {},
            "Xã Quyết Thắng": {},
            "Xã Tân Linh": {},
            "Xã Tân Thái": {},
            "Xã Tiên Hội": {},
            "Xã Văn Yên": {},
            "Xã Vạn Thọ": {},
            "Xã Yên Lãng": {}
        },
        "Huyện Phú Lương": {
            "Thị trấn Giang Tiên": {},
            "Thị trấn Đu": {},
            "Xã Cổ Lũng": {},
            "Xã Động Đạt": {},
            "Xã Hợp Thành": {},
            "Xã Ôn Lương": {},
            "Xã Phấn Mễ": {},
            "Xã Phú Đô": {},
            "Xã Phủ Lý": {},
            "Xã Tức Tranh": {},
            "Xã Vô Tranh": {},
            "Xã Yên Đổ": {},
            "Xã Yên Lạc": {},
            "Xã Yên Ninh": {},
            "Xã Yên Trạch": {}
        }
    },
    "Tuyên Quang": {
        "Thành phố Tuyên Quang": {
            "Phường Hưng Thành": {},
            "Phường Minh Xuân": {},
            "Phường Nông Tiến": {},
            "Phường Phan Thiết": {},
            "Phường Tân Hà": {},
            "Phường Tân Quang": {},
            "Phường Ỷ La": {},
            "Xã An Khang": {},
            "Xã An Tường": {},
            "Xã Đội Cấn": {},
            "Xã Lưỡng Vượng": {},
            "Xã Thái Long": {},
            "Xã Tràng Đà": {}
        },
        "Huyện Yên Sơn": {
            "Thị trấn Yên Sơn": {},
            "Xã Chiêu Yên": {},
            "Xã Chân Sơn": {},
            "Xã Công Đa": {},
            "Xã Đạo Viện": {},
            "Xã Đội Bình": {},
            "Xã Hoàng Khai": {},
            "Xã Hùng Lợi": {},
            "Xã Kiến Thiết": {},
            "Xã Kim Quan": {},
            "Xã Lang Quán": {},
            "Xã Lực Hành": {},
            "Xã Mỹ Bằng": {},
            "Xã Nhữ Hán": {},
            "Xã Nhữ Khê": {},
            "Xã Phú Thịnh": {},
            "Xã Phúc Ninh": {},
            "Xã Quý Quân": {},
            "Xã Thái Bình": {},
            "Xã Tiến Bộ": {},
            "Xã Trung Minh": {},
            "Xã Trung Môn": {},
            "Xã Trung Sơn": {},
            "Xã Trung Trực": {},
            "Xã Tứ Quận": {},
            "Xã Xuân Vân": {}
        },
        "Huyện Sơn Dương": {
            "Thị trấn Sơn Dương": {},
            "Xã Bình Yên": {},
            "Xã Cấp Tiến": {},
            "Xã Chi Thiết": {},
            "Xã Đại Phú": {},
            "Xã Đông Lợi": {},
            "Xã Đông Yên": {},
            "Xã Hào Phú": {},
            "Xã Hợp Hòa": {},
            "Xã Hợp Thành": {},
            "Xã Hồng Lạc": {},
            "Xã Lâm Xuyên": {},
            "Xã Lương Thiện": {},
            "Xã Minh Thanh": {},
            "Xã Ninh Lai": {},
            "Xã Phú Lương": {},
            "Xã Phúc Ứng": {},
            "Xã Quyết Thắng": {},
            "Xã Sơn Nam": {},
            "Xã Tam Đa": {},
            "Xã Tân Long": {},
            "Xã Thiện Kế": {},
            "Xã Thượng Âm": {},
            "Xã Trung Yên": {},
            "Xã Tuân Lộ": {},
            "Xã Văn Phú": {},
            "Xã Vân Sơn": {},
            "Xã Vĩnh Lợi": {}
        },
        "Huyện Hàm Yên": {
            "Thị trấn Tân Yên": {},
            "Xã Bạch Xa": {},
            "Xã Bằng Cốc": {},
            "Xã Bình Xa": {},
            "Xã Cường Quốc": {},
            "Xã Đức Ninh": {},
            "Xã Hùng Đức": {},
            "Xã Minh Dân": {},
            "Xã Minh Hương": {},
            "Xã Minh Khương": {},
            "Xã Nhân Mục": {},
            "Xã Phù Lưu": {},
            "Xã Tân Thành": {},
            "Xã Thái Hòa": {},
            "Xã Thái Sơn": {},
            "Xã Thành Long": {},
            "Xã Yên Lâm": {},
            "Xã Yên Phú": {},
            "Xã Yên Thuận": {}
        },
        "Huyện Chiêm Hóa": {
            "Thị trấn Vĩnh Lộc": {},
            "Xã Bình Nhân": {},
            "Xã Bình Phú": {},
            "Xã Hà Lang": {},
            "Xã Hòa An": {},
            "Xã Hòa Phú": {},
            "Xã Hùng Mỹ": {},
            "Xã Kiên Đài": {},
            "Xã Kim Bình": {},
            "Xã Linh Phú": {},
            "Xã Ngọc Hội": {},
            "Xã Nhân Lý": {},
            "Xã Phú Bình": {},
            "Xã Phúc Sơn": {},
            "Xã Phúc Thịnh": {},
            "Xã Tân An": {},
            "Xã Tân Mỹ": {},
            "Xã Tân Thịnh": {},
            "Xã Tri Phú": {},
            "Xã Trung Hà": {},
            "Xã Trung Hòa": {},
            "Xã Vinh Quang": {},
            "Xã Xuân Quang": {},
            "Xã Yên Lập": {},
            "Xã Yên Nguyên": {}
        },
        "Huyện Na Hang": {
            "Thị trấn Na Hang": {},
            "Xã Côn Lôn": {},
            "Xã Đà Vị": {},
            "Xã Hồng Thái": {},
            "Xã Khau Tinh": {},
            "Xã Năng Khả": {},
            "Xã Sinh Long": {},
            "Xã Sơn Phú": {},
            "Xã Thanh Tương": {},
            "Xã Thượng Giáp": {},
            "Xã Thượng Nông": {},
            "Xã Yên Hoa": {}
        },
        "Huyện Lâm Bình": {
            "Thị trấn Lăng Can": {},
            "Xã Bình An": {},
            "Xã Hồng Quang": {},
            "Xã Khuôn Hà": {},
            "Xã Phúc Yên": {},
            "Xã Thổ Bình": {},
            "Xã Thượng Lâm": {},
            "Xã Xuân Lập": {}
        }
    },
    "Lạng Sơn": {
        "Thành phố Lạng Sơn": {
            "Phường Chi Lăng": {},
            "Phường Đông Kinh": {},
            "Phường Hoàng Văn Thụ": {},
            "Phường Tam Thanh": {},
            "Phường Vĩnh Trại": {},
            "Xã Hoàng Đồng": {},
            "Xã Mai Pha": {},
            "Xã Quảng Lạc": {}
        },
        "Huyện Tràng Định": {
            "Thị trấn Thất Khê": {},
            "Xã Cao Minh": {},
            "Xã Chi Lăng": {},
            "Xã Chí Minh": {},
            "Xã Đại Đồng": {},
            "Xã Đào Viên": {},
            "Xã Đề Thám": {},
            "Xã Đoàn Kết": {},
            "Xã Đội Cấn": {},
            "Xã Hùng Sơn": {},
            "Xã Hùng Việt": {},
            "Xã Kháng Chiến": {},
            "Xã Khánh Long": {},
            "Xã Kim Đồng": {},
            "Xã Quốc Khánh": {},
            "Xã Quốc Việt": {},
            "Xã Tân Minh": {},
            "Xã Tân Tiến": {},
            "Xã Tân Yên": {},
            "Xã Tri Phương": {},
            "Xã Trung Thành": {},
            "Xã Vĩnh Tiến": {}
        },
        "Huyện Bình Gia": {
            "Thị trấn Bình Gia": {},
            "Xã Bình La": {},
            "Xã Hoa Thám": {},
            "Xã Hồng Phong": {},
            "Xã Hồng Thái": {},
            "Xã Minh Khai": {},
            "Xã Mông Ân": {},
            "Xã Quang Trung": {},
            "Xã Quý Hòa": {},
            "Xã Tân Hòa": {},
            "Xã Tân Văn": {},
            "Xã Thiện Hòa": {},
            "Xã Thiện Long": {},
            "Xã Thiện Thuật": {},
            "Xã Tô Hiệu": {},
            "Xã Vĩnh Yên": {},
            "Xã Yên Lỗ": {}
        },
        "Huyện Văn Lãng": {
            "Thị trấn Na Sầm": {},
            "Xã Bắc La": {},
            "Xã Gia Miễn": {},
            "Xã Hội Hoan": {},
            "Xã Hoàng Việt": {},
            "Xã Hoàng Văn Thụ": {},
            "Xã Hồng Thái": {},
            "Xã Nhạc Kỳ": {},
            "Xã Tân Lang": {},
            "Xã Tân Tác": {},
            "Xã Tân Thanh": {},
            "Xã Tân Việt": {},
            "Xã Thanh Long": {},
            "Xã Thành Hòa": {},
            "Xã Thuận Lợi": {},
            "Xã Trùng Khánh": {},
            "Xã Trùng Quán": {}
        },
        "Huyện Cao Lộc": {
            "Thị trấn Cao Lộc": {},
            "Thị trấn Đồng Đăng": {},
            "Xã Bảo Lâm": {},
            "Xã Bình Trung": {},
            "Xã Cao Lâu": {},
            "Xã Công Sơn": {},
            "Xã Gia Cát": {},
            "Xã Hải Yến": {},
            "Xã Hòa Cư": {},
            "Xã Hồng Phong": {},
            "Xã Hợp Thành": {},
            "Xã Lộc Yên": {},
            "Xã Mẫu Sơn": {},
            "Xã Phú Xá": {},
            "Xã Song Giáp": {},
            "Xã Tân Liên": {},
            "Xã Tân Thành": {},
            "Xã Thạch Đạn": {},
            "Xã Thanh Lòa": {},
            "Xã Thụy Hùng": {},
            "Xã Xuân Long": {},
            "Xã Yên Trạch": {}
        },
        "Huyện Văn Quan": {
            "Thị trấn Văn Quan": {},
            "Xã Bình Phúc": {},
            "Xã Chu Túc": {},
            "Xã Đại An": {},
            "Xã Đồng Giáp": {},
            "Xã Hòa Bình": {},
            "Xã Hữu Lễ": {},
            "Xã Lương Năng": {},
            "Xã Phú Mỹ": {},
            "Xã Song Khánh": {},
            "Xã Tân Đoàn": {},
            "Xã Tràng Các": {},
            "Xã Tràng Phái": {},
            "Xã Trấn Ninh": {},
            "Xã Tri Lễ": {},
            "Xã Tú Xuyên": {},
            "Xã Văn An": {},
            "Xã Xuân Mai": {},
            "Xã Yên Phúc": {}
        },
        "Huyện Bắc Sơn": {
            "Thị trấn Bắc Sơn": {},
            "Xã Bắc Quỳnh": {},
            "Xã Chiến Thắng": {},
            "Xã Chiêu Vũ": {},
            "Xã Đồng Ý": {},
            "Xã Hưng Vũ": {},
            "Xã Hữu Vĩnh": {},
            "Xã Long Đống": {},
            "Xã Nhất Hòa": {},
            "Xã Nhất Tiến": {},
            "Xã Quỳnh Sơn": {},
            "Xã Tân Hương": {},
            "Xã Tân Lập": {},
            "Xã Tân Thành": {},
            "Xã Tân Tri": {},
            "Xã Trấn Yên": {},
            "Xã Vạn Thủy": {},
            "Xã Vũ Lăng": {},
            "Xã Vũ Lễ": {},
            "Xã Vũ Sơn": {}
        },
        "Huyện Hữu Lũng": {
            "Thị trấn Hữu Lũng": {},
            "Xã Cai Kinh": {},
            "Xã Đồng Tân": {},
            "Xã Đồng Tiến": {},
            "Xã Đô Lương": {},
            "Xã Hòa Bình": {},
            "Xã Hồ Sơn": {},
            "Xã Hữu Liên": {},
            "Xã Minh Hòa": {},
            "Xã Minh Sơn": {},
            "Xã Minh Tiến": {},
            "Xã Nhật Tiến": {},
            "Xã Quyết Thắng": {},
            "Xã Sơn Hà": {},
            "Xã Tân Lập": {},
            "Xã Tân Thành": {},
            "Xã Thanh Sơn": {},
            "Xã Thiện Tân": {},
            "Xã Vân Nham": {},
            "Xã Yên Bình": {},
            "Xã Yên Sơn": {},
            "Xã Yên Thịnh": {},
            "Xã Yên Vượng": {}
        },
        "Huyện Chi Lăng": {
            "Thị trấn Chi Lăng": {},
            "Thị trấn Đồng Mỏ": {},
            "Xã Bắc Thủy": {},
            "Xã Bằng Hữu": {},
            "Xã Bằng Mạc": {},
            "Xã Chiến Thắng": {},
            "Xã Gia Lộc": {},
            "Xã Hòa Bình": {},
            "Xã Hùng Sơn": {},
            "Xã Lâm Sơn": {},
            "Xã Liên Sơn": {},
            "Xã Mai Sao": {},
            "Xã Nhân Lý": {},
            "Xã Quan Sơn": {},
            "Xã Quang Lang": {},
            "Xã Thượng Cường": {},
            "Xã Vân An": {},
            "Xã Vân Thủy": {},
            "Xã Vạn Linh": {},
            "Xã Y Tịch": {}
        },
        "Huyện Lộc Bình": {
            "Thị trấn Lộc Bình": {},
            "Thị trấn Na Dương": {},
            "Xã Ái Quốc": {},
            "Xã Bằng Khánh": {},
            "Xã Đông Quan": {},
            "Xã Hiệp Hạ": {},
            "Xã Hữu Khánh": {},
            "Xã Hữu Lân": {},
            "Xã Khuất Xá": {},
            "Xã Lợi Bác": {},
            "Xã Lục Thôn": {},
            "Xã Mẫu Sơn": {},
            "Xã Minh Phát": {},
            "Xã Nam Quan": {},
            "Xã Nhượng Bạn": {},
            "Xã Quan Bản": {},
            "Xã Sàn Viên": {},
            "Xã Tam Gia": {},
            "Xã Tĩnh Bắc": {},
            "Xã Tú Đoạn": {},
            "Xã Tú Mịch": {},
            "Xã Vân Mộng": {},
            "Xã Xuân Dương": {},
            "Xã Xuân Lễ": {},
            "Xã Xuân Mãn": {},
            "Xã Xuân Tình": {},
            "Xã Yên Khoái": {}
        },
        "Huyện Đình Lập": {
            "Thị trấn Đình Lập": {},
            "Thị trấn NT Thái Bình": {},
            "Xã Bắc Lãng": {},
            "Xã Bính Xá": {},
            "Xã Châu Sơn": {},
            "Xã Cường Lợi": {},
            "Xã Đình Lập": {},
            "Xã Đồng Thắng": {},
            "Xã Kiên Mộc": {},
            "Xã Lâm Ca": {},
            "Xã Thái Bình": {}
        }
    }
};

export default administrativeData;